### PR TITLE
kSPMTight fix

### PR DESCRIPTION
**Pull request by K0lb3**
SpritePackingMode.kSPMTight can occur outside of settingsRaw.packed == 1.

[sample file](https://cdn.discordapp.com/attachments/603359898507673632/678238497894563860/kuroyukiwedding_base_1_a)
from Dengeki Bunko: Crossing Void

without fix
with fix

### CODE REVIEW

**Comment by Perfare** [comment]
This is a very confusing situation and I think I need more examples to decide whether to make changes.

**Comment by AyanamiRei1** [comment]
So far every every file I've tried with this they're displaying correctly unlike they were before for example this costume character this was before 
image

and this was after 
image

**Comment by K0lb3** [comment]
I've run a small script over a bunch of games I mined. Most of them use Tight in combination with packed, but some of them have a few Sprites with Tight but without packed as well.

The game Phantom of the Kill actually uses the combination of not packed and tight a lot.

This [file](https://github.com/Perfare/AssetStudio/files/4242332/tight_list_potk.txt) contains a list of which displays

path - sprite data name
Packed , Rotation and PackingMode (Tight: 0 = SpritePackingMode.kSPMTight)

of sprite assets that aren't packed but use Tight.

Here are some samples:
[Tight.zip](https://github.com/Perfare/AssetStudio/files/4242361/Tight.zip)

From my observation so far the polygons usually simply cover the while Sprite area - but as we can see in the images above this doesn't always have to be the case.

**Comment by Perfare** [comment]
Accept this change, thank you for your help.

**Pull request merged**
