### PR TITLE
Fixes and enhancements

### PR DESCRIPTION
**Pull request by fireundubh**
## MonoScript and MonoBehaviour Support
- Fixed an issue where GetScriptString did not completely dump MonoBehaviour types
- Removed redundant "Array Array" string from MonoBehaviour output
- Truncated GUIStyle[] output because GUIStyle is not yet supported
- Added text preview for MonoScript header data
- Added text export for MonoScript header data
- Added m_ExecutionOrder, m_ClassName, m_Namespace, m_AssemblyName, and m_IsEditorScript to MonoScript output
- Added proper export path handling for MonoScript and MonoBehaviour text files
- Added proper export path handling for MonoScript and MonoBehaviour raw files
- Added "export selected assets to raw files" to context menu

## Asset List View
- Show MonoScript namespace and assembly in asset list view
- Show MonoBehaviour namespace, class, and assembly in asset list view
- Added "select all" shortcut (Ctrl+A) to preview text box
- Added fast "select all" shortcut (Ctrl+A) to asset list view
- Added fast "select all" to asset list view context menu
- Added "# item/s selected" to export asset context menu item
- Added plural labels for export asset context menu items
- Added export asset context menu strings to resources

## Searching
- Added live search toggle setting (defaults to off)
- Added search on keydown
- Added simple way to search Type column in asset list view (search: `type:your query terms here`)

## Performance/Stability/Usability
- Added automatic module loading, fallback to prompt
- Sorted Filter Type dropdown menu
- Fixed various null reference exceptions
- Disabled weird column resize behavior

## Miscellaneous
I had to change the `sceneTreeView` type to `TreeView` instead of `GOHierarchy` because I couldn't load `AssetStudioForm.cs` in the VS2017 designer.

Maybe there's another way to handle `WM_LBUTTONDBLCLK` without breaking the designer. I disabled LabelEdit for the Asset List View to try to imitate what you were doing.

### CODE REVIEW

**Comment by Tosyk** [comment]
fireundubh, thanks for this update!
can you tell more about 'Disabled weird column resize behavior'?

**Comment by fireundubh** [comment]
> fireundubh, thanks for this update!
> can you tell more about 'Disabled weird column resize behavior'? I used to sort first by size and then by type — it help me to sort meshes by size amoung meshes sorting group.

It's a GUI thing unrelated to sorting.

```csharp
assetListView.AutoResizeColumn(1, ColumnHeaderAutoResizeStyle.HeaderSize);
assetListView.AutoResizeColumn(1, ColumnHeaderAutoResizeStyle.ColumnContent);
assetListView.AutoResizeColumn(2, ColumnHeaderAutoResizeStyle.HeaderSize);
assetListView.AutoResizeColumn(2, ColumnHeaderAutoResizeStyle.ColumnContent);

var vscrollwidth = SystemInformation.VerticalScrollBarWidth;
var hasvscroll = (visibleAssets.Count / (float)assetListView.Height) > 0.0567f;
columnHeaderName.Width = assetListView.Width - columnHeaderType.Width - columnHeaderSize.Width - (hasvscroll ? (5 + vscrollwidth) : 5);
```

None of that is particularly useful, as far as I can tell, and it seems to just dock all columns (except the first) to the vertical scrollbar.

I replaced that with:

```csharp
assetListView.AutoResizeColumns(ColumnHeaderAutoResizeStyle.ColumnContent);
```

But it'd probably be better if column widths were stored in settings.

**Comment by JuGGerNaunT** [comment]
Hey. Keep going, it is really nice to have someone else who try to improve asset studio.
I just want to say about some issues in your pull request.
1) Filter doesn't work if you put space after "type: "
2) Column width in Asset List tab set based on max width of elements currently visible on the screen. It isn't convenient since you need to change width manually when you scroll down and see wider elements.
3) Column's width resets every time you change sorting order.

**Comment by Tosyk** [comment]
> 2. Column width in Asset List tab set based on max width of elements currently visible on the screen. It isn't convenient since you need to change width manually when you scroll down and see wider elements.

regarding this comment I'd like to say that this is a common behavior. On top of that most of the time the longer asset will change width of the column to maximum so other columns will be moved out of the Asset List and you have to use scroll and then change the width manually to see all columns — that's a worst case in my opinion

but I would vote for this:
> 3. Column's width resets every time you change sorting order

**Comment by fireundubh** [comment]
> 1. Filter doesn't work if you put space after "type: "

It does work. It's just not finding any matches for your query term preceded by a space. Try: `type: UnityEngine`. It's not meant to be advanced search, and it's just as strict as Name search.

> 2. Column width in Asset List tab set based on max width of elements currently visible on the screen. It isn't convenient since you need to change width manually when you scroll down and see wider elements.
> 3. Column's width resets every time you change sorting order.

This is why I said persistence would be better. What does that mean?

You'd change your column widths to how you like them, and they'd stay that way - even across sessions - until _you_ change them. I am not a fan of auto resizing, as it does now in my build and Perfare's build. UX should be designed around "explicit intent," meaning the user tells the UI how to behave and not the other way around.

**Comment by JuGGerNaunT** [comment]
I mean that it is ok to put space between or after type name. There is no type that starts or ends with space character. In any case, I do not insist to do it. The best way to get what you want is to do it yourself.

**Comment by MisterPrawn** [comment]
You wouldn't happen to know how to work with model export for AssetStudio, would you? Because Ghostbusters World, while it does have AssetStudio support, has problems with fbx file exporting. The problem is that the mesh is rigged to only one bone, so it's not exporting correctly. Must be some different and newer Unity format that causes it, but that's just a hunch.

Sorry for bringing this up a third time in this project, but that's just how it rolls, I suppose. Sample files, in case needed: https://mega.nz/#!0Yww2ShK!83VtmFTfTsCN57plC5DPTRUq9dnpgizju7OZRmNZ3Kk

**Comment by fireundubh** [comment]
@MisterPrawn I have no experience with or knowledge of the FBX format, and mesh export involves a lot of math in which I'm not proficient, so I can't help with that.

**Comment by MisterPrawn** [comment]
@fireundubh Okay, no worries. I was just curious if you knew how.

**Comment by Perfare** [comment]
Hi, @fireundubh 
First of all, thank you for your help. 
But I have a suggestion. When modifying multiple features, it should be divided into multiple pulls instead of all ones. Otherwise, when one of them is controversial, it is difficult to decide whether to merge or not.
Here are some of the controversial parts:

- Unnecessary null reference check:
https://github.com/Perfare/AssetStudio/blob/1fcfa6492f54da3b8f4dc29a4ffe55dad2a0af3c/AssetStudio/AssetStudioForm.cs#L196
https://github.com/Perfare/AssetStudio/blob/1fcfa6492f54da3b8f4dc29a4ffe55dad2a0af3c/AssetStudio/AssetStudioForm.cs#L199
https://github.com/Perfare/AssetStudio/blob/1fcfa6492f54da3b8f4dc29a4ffe55dad2a0af3c/AssetStudio/AssetStudioForm.cs#L215
https://github.com/Perfare/AssetStudio/blob/1fcfa6492f54da3b8f4dc29a4ffe55dad2a0af3c/AssetStudio/AssetStudioForm.cs#L1742
they can't be null after class instantiated.
- Type column search
To use this feature you need to type the full type name, but there is already a "Filter Type" feature and can filter multiple types at the same time.
- Strings to resources
I don't agree with this because it makes the changes more cumbersome and has no benefit in terms of performance.
- Modify the structure of the export folder
https://github.com/Perfare/AssetStudio/blob/1fcfa6492f54da3b8f4dc29a4ffe55dad2a0af3c/AssetStudio/StudioClasses/Studio.cs#L519
https://github.com/Perfare/AssetStudio/blob/1fcfa6492f54da3b8f4dc29a4ffe55dad2a0af3c/AssetStudio/StudioClasses/Studio.cs#L527
I think it’s good now, no need to change it.

In addition, you modified the GetScriptString function, but I am sorry that this feature is experimental and unfinished, although it works fine in most cases. I have decided to perfect or rewrite it, but not now, my current plan is to separate the UI code and organize the AssetStudio core code into a library. Hope I can finish it as soon as possible.

**Comment by fireundubh** [comment]
I don't agree with your assessment. I'm perfectly happy to work on my own fork rather than contribute any code to your project.

We've already made a ton of changes, including a progress bar that makes sense and using a TreeView and iterative node reader for Mono assets.

**Comment by Perfare** [comment]
OK.

**Comment by fireundubh** [comment]
FYI:

- AssetStudio crashes on load without those null checks, so your assumption is wrong.
- Searching for keywords in the Type column is vastly different from filtering types. Sometimes you want to see assets whose type names match a keyword query, not see only assets belonging to specific types.
- A singular place to manage localization is far less cumbersome than digging through source code to find and change strings and formats.

**Pull request closed without merging**
